[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "test_package"
version = "0.1.0"
description = "Test"
authors = [
  { name="Connor Quick", email="name@example.com"  },
]
readme = "README.md"
